config/routes.rb
Rails.application.routes.draw do
  # set the index page / root url
  root 'pages#home'
  get 'pages/about'
  get 'pages/home'
  get 'pages/portfolio'
  get 'pages/cool_new_projects'
  get 'pages/contact'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def home
  end

  def contact
  end

  def portfolio
  end

  def cool_new_projects
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= link_to "Home", root_path %>
    <%= link_to "About", pages_about_path %>
    <%= link_to "Portfolio", pages_portfolio_path %>
    <%= link_to "Cool New Projects", pages_cool_new_projects_path %>
    <%= link_to "Contact", pages_contact_path %>


        <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/cool_new_projects.html.erb
<h1>Pages#cool_new_projects</h1>
<p>Find me in app/views/pages/cool_new_projects.html.erb</p>

app/views/pages/home.html.erb
<h1>Hello World</h1>
<%= "Hello World!" %> <!-- '=' is needed to render to a screen -->
<% 'Hello World' %> <!-- this renders on the server but never shows on the client -->

app/views/pages/portfolio.erb
<h1>Pages#Portofolio</h1>
<p>Find me in app/views/pages/portfolio.html.erb</p>